module.exports = {
	htmlcss: [
		{
			type: 'doc',
			id: 'htmlcss/index',
		},
		{ type: 'doc', id: 'htmlcss/resources' },
		{
			type: 'category',
			label: 'HTML',
			items: [
				'htmlcss/html/semantic',
				'htmlcss/html/meta',
				'htmlcss/html/doctype',
				'htmlcss/html/iframe',
				{
					type: 'category',
					label: '面试题',
					items: [
						'htmlcss/html/questions/1',
						'htmlcss/html/questions/2',
						'htmlcss/html/questions/3',
						'htmlcss/html/questions/4',
						'htmlcss/html/questions/5',
						'htmlcss/html/questions/6',
						'htmlcss/html/questions/7',
						'htmlcss/html/questions/8',
					],
				},
			],
		},
		{
			type: 'category',
			label: 'CSS',
			items: [
				'htmlcss/css/selectors',
				'htmlcss/css/units',
				'htmlcss/css/float',
				'htmlcss/css/display',
				'htmlcss/css/bfc',
				'htmlcss/css/box-model',
				'htmlcss/css/flex',
				'htmlcss/css/z-index',
				'htmlcss/css/pseudo',
				'htmlcss/css/line-height',
				'htmlcss/css/img',
				'htmlcss/css/ellipsis',
				'htmlcss/css/shapes',
				'htmlcss/css/mobile-layout',
				'htmlcss/css/1px',
				'htmlcss/css/bem',
				'htmlcss/css/postcss',
				'htmlcss/css/v-center',
				'htmlcss/css/h-center',
				'htmlcss/css/vh-center',
				'htmlcss/css/layouts',
				{
					type: 'category',
					label: '面试题',
					items: [
						'htmlcss/css/questions/1',
						'htmlcss/css/questions/2',
						'htmlcss/css/questions/3',
						'htmlcss/css/questions/4',
						'htmlcss/css/questions/5',
						'htmlcss/css/questions/6',
						'htmlcss/css/questions/7',
						'htmlcss/css/questions/8',
						'htmlcss/css/questions/9',
						'htmlcss/css/questions/10',
						'htmlcss/css/questions/11',
						'htmlcss/css/questions/12',
					],
				},
			],
		},
	],
	javascript: [
		{
			type: 'doc',
			id: 'javascript/index',
		},
		{
			type: 'category',
			label: '基础',
			items: ['javascript/types', 'javascript/hoisting'],
		},
	],
	books: [
		{ type: 'doc', id: 'books/index' },
		{
			type: 'category',
			label: 'CSS',
			items: ['books/css/1'],
		},
	],
};
